[features]
seeds = false
[programs.devnet]
magic_hat = "G317XThznKMemjmSBEekMSsPedT9krKcAeRmE39drhNA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com/"
wallet = "/Users/arvindkrishnan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
